class LegadoBridgeCapability {
  const LegadoBridgeCapability._();

  /// Functions that are implemented with semantics close to Legado runtime.
  static const Set<String> fullBridgeCalls = <String>{
    'ajax',
    'ajaxall',
    'connect',
    'head',
    'get',
    'post',
    'put',
    'log',
    'setcontent',
    'getstring',
    'getstringlist',
    'getelements',
    'getelement',
    'getcookie',
    'base64decode',
    'base64encode',
    'base64decodetobytearray',
    'base64decoder',
    'md5encode',
    'md5encode16',
    'encodeuri',
    'htmlformat',
    'timeformat',
    'timeformatutc',
    'tonumchapter',
    't2s',
    's2t',
    'strtobytes',
    'bytestostring',
    'createsymmetriccrypto',
    'getwebviewua',
    'randomuuid',
    'androidid',
    'deviceid',
    'hexdecodetostring',
    'hexdecodetobytearray',
    'hexencodetostring',
    'digesthex',
    'hmachex',
    'hmacbase64',
    'desencodetobase64string',
    'aesdecodeargsbase64str',
    'tourl',
    'cachefile',
    'removecookie',
    'aesdecodetostring',
    'aesdecodetobytearray',
    'aesbase64decodetostring',
    'aesbase64decodetobytearray',
    'aesencodetostring',
    'aesencodetobytearray',
    'aesencodetobase64string',
    'aesencodetobase64bytearray',
  };

  /// Functions that are recognized, but semantics are still not fully aligned
  /// with Legado source implementation.
  static const Set<String> partialBridgeCalls = <String>{
    'toast',
    'longtoast',
    'startbrowser',
    'startbrowserawait',
    'webview',
    'webviewgetsource',
    'webviewgetoverrideurl',
    'initurl',
    'getstrresponse',
    'getresponse',
    'getheadermap',
    'regetbook',
    'refreshtocurl',
    'importscript',
    'getverificationcode',
    'createasymmetriccrypto',
    'createsign',
    'openurl',
    'utf8togbk',
    'searchbook',
    'addbook',
  };

  /// Functions intentionally not supported in appread for security/runtime cost
  /// reasons (file system / archive / font runtime helpers).
  static const Set<String> unsupportedBridgeCalls = <String>{
    'readfile',
    'getfile',
    'readtxtfile',
    'deletefile',
    'downloadfile',
    'unzipfile',
    'un7zfile',
    'unrarfile',
    'unarchivefile',
    'gettxtinfolder',
    'getzipstringcontent',
    'getrarstringcontent',
    'get7zstringcontent',
    'getzipbytearraycontent',
    'getrarbytearraycontent',
    'get7zbytearraycontent',
    'queryttf',
    'querybase64ttf',
    'replacefont',
  };

  static const Set<String> knownBridgeCalls = <String>{
    ...fullBridgeCalls,
    ...partialBridgeCalls,
  };
}
